databases:
  - name: sniffspot
    databaseName: sniffspot
    user: sniffspot

services:
  - type: web
    name: sniffspot
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sniffspot
          property: connectionString
